kind: ConfigMap
apiVersion: v1
metadata:
  name: argo-to-splunk
  namespace: argocd
data:
  config.py: |-
    splunkUrl = '{{ .Values.configmap.splunkUrl }}'
    splunkToken = '{{ .Values.configmap.splunkToken }}'
    argoUrl = '{{ .Values.configmap.argoUrl }}'
