namespace: toston

toston_app_label: toston
configmap:
  fqdn: cloudlet.dev
  image: quay.apps.{{Valuse.configmap.fqdn}}/cloudlet/toston:nginx-latest

minio_test:
  configmap:  
    fqdn: dev.cloudlet-dev.com
  image:
    repository: quay.apps.{{Valuse.configmap.fqdn}}/cloudlet
    name: toston
    tag: "minio-test-secure-latest"

quay_test:    
  image:
    repository: quay.apps.{{Valuse.configmap.fqdn}}/cloudlet
    name: toston
    tag: "quaytest-latest"

matoshon:    
  image:
    repository: quay.apps.{{Valuse.configmap.fqdn}}/cloudlet
    name: toston
    tag: "matoshon-latest"

argo_app:    
  image:
    repository: quay.apps.{{Valuse.configmap.fqdn}}/cloudlet
    name: toston
    tag: "app_argo-latest"

  every_minutes: 3

  configmap:  
    argoUrl: 'https://argocd.apps.np.cloudlet-dev.com/'
    appsApi: 'api/v1/clusters'
    authApi: 'api/v1/session'
    splunkUrl: 'https://13.90.23.80:8088/services/collector/event'
    repoApi: 'api/v1/repositories'
    cluster_name: 'np'
    reponame: 'cloudlet'
    url: 'https://argocd.apps.np.cloudlet-dev.com/'
    verifySSl: 'False'
    userName: 'admin'
    password: 'redhat'

