namespace: toston

toston_app_label: toston
configmap:
  fqdn: cloudlet.dev
  image: docker.io/nginx

minio_test:
  configmap:  
    fqdn: dev.cloudlet-dev.com
  containers:
    repository: docker.io/meshistern
    image: minio-test-secure
    version: latest


