namespace: toston

toston_app_label: toston
configmap:
  fqdn: cloudlet.dev
  image: "cloudlet-org/toston:nginx-latest"

minio_test:
  configmap:  
    fqdn: dev.cloudlet-dev.com
  image:
    repository: cloudlet-org
    name: toston
    tag: "minio-test-secure"

quay_test:    
  image:
    repository: cloudlet-org
    name: toston
    tag: "quaytest-latest"

matoshon:    
  image:
    repository: cloudlet-org
    name: toston
    tag: "matoshon-latest"

argo_app:    
  image:
    repository: cloudlet-org
    name: toston
    tag: "app_argo-latest"

  every_minutes: 3

  configmap:  
    argoUrl: 'https://argocd.apps.np.cloudlet-dev.com/'
    appsApi: 'api/v1/clusters'
    authApi: 'api/v1/session'
    splunkUrl: '{{ .Values.splunk.url }}'
    repoApi: 'api/v1/repositories'
    cluster_name: 'np'
    reponame: 'cloudlet'
    url: 'https://argocd.apps.np.cloudlet-dev.com/'
    verifySSl: 'False'
    userName: 'admin'
    password: 'redhat'

