namespace: toston

toston_app_label: toston
configmap:
  fqdn: cloudlet.dev
  image: docker.io/nginx

minio_test:
  configmap:  
    fqdn: dev.cloudlet-dev.com
  image:
    repository: meshistern
    name: minio-test-secure
    tag: latest

quay_test:    
  image:
    repository: quay.io/almoggo
    name: quaytest
    tag: "latest"

matoshon:    
  image:
    repository: hacetah726
    name: matoshon
    tag: 2

argo_app:    
  image:
    repository: snir1234
    name: app_argo
    tag: "latest"

  every_minutes: 3

  configmap:  
    argoUrl: 'https://argocd.apps.np.cloudlet-dev.com/'
    appsApi: 'api/v1/clusters'
    authApi: 'api/v1/session'
    splunkUrl: 'https://13.90.23.80:8088/services/collector/event'
    repoApi: 'api/v1/repositories'
    cluster_name: 'np'
    reponame: 'cloudlet'
    url: 'https://argocd.apps.np.cloudlet-dev.com/'
    verifySSl: 'False'
    userName: 'admin'
    password: 'redhat'

