kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.name }}-route
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.name }}-{{ .Values.namespace }}.apps.{{ .Values.clusterName }}.{{ .Values.baseDomain }}
  to:
    kind: Service
    name: minio-service
    weight: 100
  port:
    targetPort: 9000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - wildcardPolicy: None
      host: {{ .Values.name }}-{{ .Values.namespace }}.apps.{{ .Values.clusterName }}.{{ .Values.baseDomain }}
      routerCanonicalHostname: apps.{{ .Values.clusterName }}.{{ .Values.baseDomain }}
      routerName: default
