---
kind: ConfigMap
apiVersion: v1
metadata:
  name: speedtest-download-cloudlet
  namespace: speedtest-download-cloudlet
data:
  config.py: |-
    quay_repo = 'https://quay.apps.{{ .Values.configmap.fqdn }}'
    cluster_name = '{{ .Values.configmap.cluster_name }}'
    splunk_event_url = '{{ .Values.SPLUNK_URL }}'
    splunk_token = '{{ .Values.SPLUNK_TOKEN }}'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: trusted-ca
  namespace: quaylogs
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
