apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-download-cloudlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest-download
  template:
    metadata:
      labels:
        app: speedtest-download
    spec:
      containers:
      - name: speedtest-download
        image: "{{ .Values.IMAGE_NAME }}"
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: MAIN_APP_URL 
          value: "{{ .Values.MAIN_APP_URL }}"
        - name: SPLUNK_TOKEN
          value: "{{ .Values.SPLUNK_TOKEN }}"
        - name: SPLUNK_URL
          value: "{{ .Values.SPLUNK_URL }}"
        - name: MIN_CHECK_TIME
          value: "{{ .Values.MIN_CHECK_TIME }}"
        - name: OCP_NAME
          value: "{{ .Values.OCP_NAME }}"
      restartPolicy: Always
