apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-test-apps-{{ template "cluster_name" . }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: argocdod/apps/main-test-apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: configmap.Clustername
          value: {{ template "cluster_name" . }}
