kind: ConfigMap
apiVersion: v1
metadata:
  name: argo-to-splunk-config
  namespace: argocd
data:
  config.py: |+
    argoUrl = 'https://argocd-argocd.apps.ocp43-np.cloudlet-dev.com/'
    appsApi = 'api/v1/applications'
    authApi = 'api/v1/session'
    login = {"username": "admin", "password": "redhat"}
   
    splunkUrl = 'https://40.118.64.131:8088/services/collector/event'
    splunkAuth = {'Authorization': 'Splunk c92a548a-e243-41ab-9168-8a17ce013342'}
