---
# Source: quay-enterprise/templates/01_quay_project.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: quay-enterprise

---
# Source: quay-enterprise/templates/02_redhat-pull-secret.yaml
apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbVZrYUdGMEszRjFZWGs2VHpneFYxTklVbE5LVWpFMFZVRmFRa3MxTkVkUlNFcFRNRkF4VmpSRFRGZEJTbFl4V0RKRE5GTkVOMHRQTlRsRFVUbE9NMUpGTVRJMk1USllWVEZJVWc9PSIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
kind: Secret
metadata:
  annotations:
  name: redhat-pull-secret
  namespace: quay-enterprise
type: kubernetes.io/dockerconfigjson

---
# Source: quay-enterprise/templates/03_operator_group.yaml
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operator-group
  namespace: quay-enterprise
spec:
  targetNamespaces:
  - quay-enterprise

---
# Source: quay-enterprise/templates/04_operator_sub.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay
  namespace: quay-enterprise
spec:
  channel: "{{ .Values.installation.channel }}"
  name: quay
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: "{{ .Values.installation.installPlan }}"

---
# Source: quay-enterprise/templates/06_db-creds.yaml
apiVersion: v1
stringData:
  database-username: "{{ .Values.CR.secrets.db.user }}"
  database-password: "{{ .Values.CR.secrets.db.pass }}"
  database-root-password: "{{ .Values.CR.secrets.db.rootpass }}"
  database-name:  "{{ .Values.CR.secrets.db.name }}"
kind: Secret
metadata:
  annotations:
  name: db-creds
  namespace: quay-enterprise
type: Opaque

---
# Source: quay-enterprise/templates/07_quay-config-creds.yaml
apiVersion: v1
stringData:
  config-app-password: "{{ .Values.CR.secrets.quay.config.pass  }}"
kind: Secret
metadata:
  annotations:
  name: quay-config-creds
  namespace: quay-enterprise
type: Opaque

---
# Source: quay-enterprise/templates/08_quayconfigfile.yaml
apiVersion: v1
data:
  configmore.yaml: >-
    QVBQX1NQRUNJRklDX1RPS0VOX0VYUElSQVRJT046IDNtCkZFQVRVUkVfQU5PTllNT1VTX0FDQ0VTUzogZmFsc2UKRkVBVFVSRV9JTlZJVEVfT05MWV9VU0VSX0NSRUFUSU9OOiBmYWxzZQpGRUFUVVJFX1BBUlRJQUxfVVNFUl9BVVRPQ09NUExFVEU6IGZhbHNlCkZFQVRVUkVfUkVRVUlSRV9FTkNSWVBURURfQkFTSUNfQVVUSDogdHJ1ZQo=
kind: Secret
metadata:
  annotations:
  name: quayconfigfile
  namespace: quay-enterprise
type: Opaque

---
# Source: quay-enterprise/templates/09_redis-creds.yaml
apiVersion: v1
stringData:
  password: "{{ .Values.CR.secrets.redis.pass  }}"
kind: Secret
metadata:
  annotations:
  name: redis-creds
  namespace: quay-enterprise
type: Opaque

---
# Source: quay-enterprise/templates/10_super-user-quay.yaml
apiVersion: v1
stringData:
  superuser-username: "{{ .Values.CR.secrets.quay.super.user }}"
  superuser-password: "{{ .Values.CR.secrets.quay.super.pass }}"
  superuser-email: "{{ .Values.CR.secrets.quay.super.mail }}"
kind: Secret
metadata:
  annotations:
  name: super-user-quay
  namespace: quay-enterprise
type: Opaque

---
# Source: quay-enterprise/templates/11_custom-quay-tls.yaml
kind: Secret
apiVersion: v1
metadata:
  name: custom-quay-tls
  namespace: quay-enterprise
data:
  tls.crt: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg0Q0NRRFJUOWdzeFdUQnB6QU5CZ2txaGtpRzl3MEJBUXNGQURCVE1Rc3dDUVlEVlFRR0V3SlkKV0RFVk1CTUdBMVVFQnd3TVJHVm1ZWFZzZENCRGFYUjVNUXd3Q2dZRFZRUUtEQU5OVDBReEVUQVBCZ05WQkFzTQpDRU5zYjNWa2JHVjBNUXd3Q2dZRFZRUUREQU5TYmtRd0hoY05NakF3TlRFeE1USXhNVE14V2hjTk16QXdOVEE1Ck1USXhNVE14V2pCbk1Rc3dDUVlEVlFRR0V3SllXREVWTUJNR0ExVUVCd3dNUkdWbVlYVnNkQ0JEYVhSNU1Sd3cKR2dZRFZRUUtEQk5FWldaaGRXeDBJRU52YlhCaGJua2dUSFJrTVNNd0lRWURWUVFEREJvcUxuTmhiR1Z6TG14aApZaTUwYkhZdWNtVmthR0YwTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCCkFMMlhBMUIvYzRrdEVUSDZ5NDdkeDE1NCtGT1d2a2lpU2F4bTFwWWdLcGJaWGJ4N2ZlNlFJWXc3czNIQngwbGYKS2tqNHE3cFRYL3NscGdJaHc0RThQdVBhZktsUGw3U3lMT0xtdSs5MTRaemlrUlY4Um51Wit0alA5UTBVOXFydAorQWhlTnl6NzdqSjBLT3VsM3hVbERyaGd1aGVtSDBxWDlHd0I1QlhQQ1VYeFVNRVdIWDJOQmhCbnFRL0VqZGtDCm9iMEdsRFlBeHBmeUVXV0NPQkQ3RUNMalF3K1laMk9KOXlaQXN1dGczeGJjNkNzM3RiNmpWZHllTWhhTkE5Zm4KTU9jYzJsY3BkZ0d6VnlNbzE2d0ZjaDRzS2N3cVpLUnEreHhnZFdaTUxKdGlJV1FDaWZtcUd6d2FFUDVwakh2Tgo3ZFFEMmxEcTVXUFlOaWxkd1VnMDNtVUNBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUFObzZVcW1aCnJBMUovbFZKd2pKSmJWWm9NMmNoUkdDYjJPU1BYUVU5ZnRFTk5xcTlIVG5LNEE4c2FScnNCbUxhd29wcFE0ZzEKbkJVRndmZU5ZbXZkbWJkZEhuMHBzc3h5cU11ODlPRGRRd3lYc2dsTlFLdGtHU24xNUtpSGpRNGZ4MWZxdU5KUwpPZ2p4MkFVWlhRM3dsdTJoclk2bjB5WHd4aDB3ckdmQU5vTm9hTUhXYTZqOFd0azJwRXk4bjdrNTYrUnpJOE9LCjBsMlNrN2FyRUd1OXcwZzI2eElMbHZyR1FLTDU5RzNOWUdQSTFJcXJwTEZsQ2NoQUpHQWdJeWVrK1pTVXA2dXAKbHY2d1JqSitPY2wvTmJHQ0R3ZnpvZFpoUnkvNnFLL0l2L0hNby9OK29ncFR6c29zcnI2My9oSnVjOGNDcWJqTgo1Z2lkL05ER0RRVHdYZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlVENDQW1HZ0F3SUJBZ0lKQU5JNjVvWHpYRk5mTUEwR0NTcUdTSWIzRFFFQkN3VUFNRk14Q3pBSkJnTlYKQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEREQUtCZ05WQkFvTUEwMVBSREVSTUE4RwpBMVVFQ3d3SVEyeHZkV1JzWlhReEREQUtCZ05WQkFNTUExSnVSREFlRncweU1EQTFNVEV4TVRReU1UbGFGdzB6Ck1EQTFNRGt4TVRReU1UbGFNRk14Q3pBSkJnTlZCQVlUQWxoWU1SVXdFd1lEVlFRSERBeEVaV1poZFd4MElFTnAKZEhreEREQUtCZ05WQkFvTUEwMVBSREVSTUE4R0ExVUVDd3dJUTJ4dmRXUnNaWFF4RERBS0JnTlZCQU1NQTFKdQpSRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKbkV5ckZwcVNNcmJRckdmdlp1CkYwM1JSNXVwMVN2QTZOb20ySC9CbFlhK05KTlJuem0zdmZCaVNGb3dmRFRVOEsxcy9mdU03ajkzNCtBUkUvSjAKMDhRWEliS3NjanBjRE14OFBGdkpNSnlCZkRUS0ZuVERxMDdHV01QRWpmWVFDaWdKUkwrZFp2eWpDNHZWTWpzdgpCMDgrRGJobDhNSDNRWUxoeXhHSFBmUllHZ2lDNERzd015ckxtZU4vZUt2a0k3RXVEUC92LzNvSHY3T2FPLzlzCkFHdkNuS1ZEUzh1aE41TGdBeFprT3M5MDdsYXMyUWtHS202VDB1UTBoUU9jMWF2ZXZOTXh5YmswVGRBM0NEbHcKNzZjZ2lHTW1acmVNbHBHMy9JbTQ4MDBSK1Y5RGpHbDBHdElaeVpZL1g3N0VkOWpHdjZZZThjcC84b2dXNlhEQwowYk1DQXdFQUFhTlFNRTR3SFFZRFZSME9CQllFRklFWVprYy9ZYlNaQVNudUc4MUZIaTVDT3pzcE1COEdBMVVkCkl3UVlNQmFBRklFWVprYy9ZYlNaQVNudUc4MUZIaTVDT3pzcE1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFDYWNzZ2FNSlAvcDl5OVgzeC9EY01jOWVjdEpqQTN1RHcxME4xV2VGTmVqK1RDawp3bExYc05nRHVXdEF1dWI1ZXRGckNKOXJZUTRMaWtBU0RLVElnMThuWEdLVlNWcVk0TFNieU9WWGxOcDliVng0Cm1xK2tQRGhGMTFNdCtZNndacEZOUldlRFVBQkxiOTZKMDJRSlBPQjU3a0RrOTNXNDlmMWpuUzFzd2MrZFBOUlMKTUhMWWlNcWtCUEd6Zk51Y2VYOTFXSnl6dUo4cmFmclpDaWxKaXpzVGQ0VUlaVHBNbndmWnRKMTZYNTFHZG9QUApvLzM4dVZjeGZxL2xvL2pWZjNWbmpoOWpnemU5VFZtRHdJYzlZbnN0Mnp3YWM3eC95cUdJaU1KWTcvOVN0djdpCjJteVpyaUR3Y1JaRWF2MXpyY0MwSXQ5cHVtN2FnMCtpM1UzRFZYVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: >-
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdlpjRFVIOXppUzBSTWZyTGp0M0hYbmo0VTVhK1NLSkpyR2JXbGlBcWx0bGR2SHQ5CjdwQWhqRHV6Y2NISFNWOHFTUGlydWxOZit5V21BaUhEZ1R3KzQ5cDhxVStYdExJczR1YTc3M1hobk9LUkZYeEcKZTVuNjJNLzFEUlQycXUzNENGNDNMUHZ1TW5RbzY2WGZGU1VPdUdDNkY2WWZTcGYwYkFIa0ZjOEpSZkZRd1JZZApmWTBHRUdlcEQ4U04yUUtodlFhVU5nREdsL0lSWllJNEVQc1FJdU5ERDVoblk0bjNKa0N5NjJEZkZ0em9LemUxCnZxTlYzSjR5Rm8wRDErY3c1eHphVnlsMkFiTlhJeWpYckFWeUhpd3B6Q3BrcEdyN0hHQjFaa3dzbTJJaFpBS0oKK2FvYlBCb1EvbW1NZTgzdDFBUGFVT3JsWTlnMktWM0JTRFRlWlFJREFRQUJBb0lCQUU2N2Q5VG1HTVRPd21WUApFVm16SUNoTGRGVENOU05Vd2VPbWtWYW01UWpnRzkwNks0SDJ1UGZUa3lHYXAzZ0EzVDZRaGtCS2Y0RjhrUVF4Cm9VNzZCZVA1eCt0SDhtaEgxZndrZGNkcjNOV2FBVVk2NWNwT2w2MlNMdUhQNHQvNUV4Zm1pR05WL0FWWDErYUUKYTdBTVE2Q3VDcG5ua3ZjWFE1blc3ekZmV1NxQjVVRDNQZHE0TGFCTGVhRnMrNXQrV1pFM3M4Yk9HSjg1UmRXQgpBVTVNV1liS1BlWSt4a0xwTG5UMkNMTUFEcTFRUmJlbTR6cGx2WXhPQ0k1OXFmamtWS2tBeHBsTEhiK1ZwUW0rClVHanlEemxhRGtmcXFlR2prRDdBZ0dqNkZaNVhLaEpUMFYzOWo3NFFid2JGc1haOUp2WHBPaUhENk9MQmZlbG8KUUtyUDZjRUNnWUVBNUFFREVvbmdyb2NuNmFrMGMvczQrVDBNNFpZc0QyNGl2K1VZZisrWjV1UUV2bUx0aWNNQQpuTkF3dTJscTd2THQ5RE02eFhHMDNNZXUzQUNxWTNkSldtWTkvblNtUktrVnZnM3BZcWdwY0p0S2t4Ynp0S1pMClZiTUxxMkZzU0lJWjJOZGJwbnhtR1NxRUFZRWhING5zVi9OVDdwMkNyZUxxMkN5K0t4VTlLV01DZ1lFQTFONkMKSDJhL3JZclJvNVpjRGxsQkczeForSGhoNDd5SGU0Q21UbngwTTNNMUtYZVNoSVB5WTRpOUVFRlFYMkpta2w3UApyN2xiZ3JITUV0aEZ1ZWFUeHdicUpuQWQxeGlmRHpza2JCRTdDM3pHSUQ3OHVtbDBOWkdCOG1vUDZlT1ZqNldCCkZCVnVVZC9yYTlRVHJGZFV2ZUc5S2c0R3ZrbmxyM1NEZjc3dFI1Y0NnWUFTOUNLVlAvRDFrVGE0TGVDMlk0UHcKOUNwRjluM2pLbnlwQnhwcVNEaTdBT21FQ2lWRTluanVrRC84MUY2WFRvcUphbGpRWVF0djd3bVNNRnY1dU1qWQpRdmVVVjQ0YTF4Ti9vUmh0b3gwT3gxb0RzRHpDSDdEVGh2YkpZR2ZuL3lpMjVmQXdmdGJkOExMWWpTdDd1N054Ci9FQlY3YklYVW0zRFdyVFVVQWV0a1FLQmdGQ2hWN2g5T3UySlA0OHZUUDlDWDU4Qm96S3lwcUdVcjl6Z0JoNkUKbFo5SGJFT2d2eWJpczlWdjNlMWlVQWRSUm5qNjRNQTIvYXFybmhrbFFvUUFDc25Bbk1DaWh5c0tjSFZjZVpkVgpqMy95YXptYm9pOFo4cUszMHZqM283OThMUktVSmlodFZiUTlsUGJyQmVpcHk3ZUE0aDRqNGZvQ0U3WTU4L1ZYClpKbFJBb0dBUjVRMXJNaWJ6T3Y0dFkyRklvbVBMWDJZQjdnRmNhNzZDTXJHVVdxNlRPcnBrUjAyUFlrOEE4aUcKcXpSdkdsTWRLOWNqQ09ZSDI4QWVnUXZ2VWo0dGczallWR1o0azN1UFlDQjdJNlN0azdBRlAyU21mM3Q3aFRyeQpZNVUzN2xjU0lBVTBnTjk4VDdBZnNlQjl2dTZwaUZTc3BrbXA1c0xTRHlSQ0MzbVRucGc9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
type: kubernetes.io/tls

---
# Source: quay-enterprise/templates/12_trust-ca.yaml
kind: Secret
apiVersion: v1
metadata:
  name: trust-ca
  namespace: quay-enterprise
data:
  rootCA.pem: >-
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlVENDQW1HZ0F3SUJBZ0lKQU5JNjVvWHpYRk5mTUEwR0NTcUdTSWIzRFFFQkN3VUFNRk14Q3pBSkJnTlYKQkFZVEFsaFlNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEREQUtCZ05WQkFvTUEwMVBSREVSTUE4RwpBMVVFQ3d3SVEyeHZkV1JzWlhReEREQUtCZ05WQkFNTUExSnVSREFlRncweU1EQTFNVEV4TVRReU1UbGFGdzB6Ck1EQTFNRGt4TVRReU1UbGFNRk14Q3pBSkJnTlZCQVlUQWxoWU1SVXdFd1lEVlFRSERBeEVaV1poZFd4MElFTnAKZEhreEREQUtCZ05WQkFvTUEwMVBSREVSTUE4R0ExVUVDd3dJUTJ4dmRXUnNaWFF4RERBS0JnTlZCQU1NQTFKdQpSRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKbkV5ckZwcVNNcmJRckdmdlp1CkYwM1JSNXVwMVN2QTZOb20ySC9CbFlhK05KTlJuem0zdmZCaVNGb3dmRFRVOEsxcy9mdU03ajkzNCtBUkUvSjAKMDhRWEliS3NjanBjRE14OFBGdkpNSnlCZkRUS0ZuVERxMDdHV01QRWpmWVFDaWdKUkwrZFp2eWpDNHZWTWpzdgpCMDgrRGJobDhNSDNRWUxoeXhHSFBmUllHZ2lDNERzd015ckxtZU4vZUt2a0k3RXVEUC92LzNvSHY3T2FPLzlzCkFHdkNuS1ZEUzh1aE41TGdBeFprT3M5MDdsYXMyUWtHS202VDB1UTBoUU9jMWF2ZXZOTXh5YmswVGRBM0NEbHcKNzZjZ2lHTW1acmVNbHBHMy9JbTQ4MDBSK1Y5RGpHbDBHdElaeVpZL1g3N0VkOWpHdjZZZThjcC84b2dXNlhEQwowYk1DQXdFQUFhTlFNRTR3SFFZRFZSME9CQllFRklFWVprYy9ZYlNaQVNudUc4MUZIaTVDT3pzcE1COEdBMVVkCkl3UVlNQmFBRklFWVprYy9ZYlNaQVNudUc4MUZIaTVDT3pzcE1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFDYWNzZ2FNSlAvcDl5OVgzeC9EY01jOWVjdEpqQTN1RHcxME4xV2VGTmVqK1RDawp3bExYc05nRHVXdEF1dWI1ZXRGckNKOXJZUTRMaWtBU0RLVElnMThuWEdLVlNWcVk0TFNieU9WWGxOcDliVng0Cm1xK2tQRGhGMTFNdCtZNndacEZOUldlRFVBQkxiOTZKMDJRSlBPQjU3a0RrOTNXNDlmMWpuUzFzd2MrZFBOUlMKTUhMWWlNcWtCUEd6Zk51Y2VYOTFXSnl6dUo4cmFmclpDaWxKaXpzVGQ0VUlaVHBNbndmWnRKMTZYNTFHZG9QUApvLzM4dVZjeGZxL2xvL2pWZjNWbmpoOWpnemU5VFZtRHdJYzlZbnN0Mnp3YWM3eC95cUdJaU1KWTcvOVN0djdpCjJteVpyaUR3Y1JaRWF2MXpyY0MwSXQ5cHVtN2FnMCtpM1UzRFZYVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
type: Opaque

---
# Source: quay-enterprise/templates/13_redhatcop_v1alpha1_quayecosystem_cr.yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
  namespace: quay-enterprise
spec:
  quay:
    superuserCredentialsSecretName: super-user-quay
    configSecretName: quay-config-creds
    imagePullSecretName: redhat-pull-secret
    persistentVolumeSize: "{{ .Values.CR.quay.persistentVolumeSize }}Gi"
    database:
      credentialsSecretName: db-creds
    enableRepoMirroring: true
    repoMirrorTLSVerify: false
    configFiles:
      - secretName: quayconfigfile
      - secretName: trust-ca
        type: extraCaCert
    livenessProbe:
      initialDelaySeconds: 420
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
    readinessProbe:
      initialDelaySeconds: 420
      httpGet:
        path: /health/instance
        port: 8443
        scheme: HTTPS
    externalAccess:
      tls:
        secretName: custom-quay-tls
  redis:
    credentialsSecretName: redis-creds
    imagePullSecretName: redhat-pull-secret
  clair:
    enabled: false
    imagePullSecretName: redhat-pull-secret
    updateInterval: "{{ .Values.CR.clair.updateInterval }}"

#add under db:       volumeSize: "{{ .Values.CR.db.volumeSize }}Gi"
