kind: ConfigMap
apiVersion: v1
metadata:
  name: main-test-apps
  namespace: main-test-apps
data:
  config.py: |+
    splunkUrl = '{{ .Values.configmap.splunkUrl }}'
    clusterName = '{{ .Values.configmap.clusterName }}'
    splunkToken = '{{ .Values.configmap.splunkToken }}'
    servicesRoutes = {{ .Values.configmap.servicesRoutes }}
