kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgrest
  namespace: {{ .Values.namespace }}
  labels: {}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgrest
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: postgrest
        deploymentconfig: postgrest
    spec:
      containers:
        - name: postgrest
          securityContext: {}
          image: postgrest/postgrest:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          env:
            - name: PGRST_DB_URI
              value: >-
                host={{ .Values.db.host }} port={{ .Values.db.port }}
                dbname={{ .Values.db.name }} user={{ .Values.db.user }}
                password={{ .Values.db.pass }} sslmode=require
            - name: PGRST_DB_ANON_ROLE
              value: {{ .Values.db.role }}
            - name: PGRST_DB_SCHEMA
              value: {{ .Values.db.schema }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
status: {}
