apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collectorforopenshift
  namespace: {{ .Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: argocdod/apps/collectorforopenshift
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  helm:
    valueFiles:
      - values.yaml
