apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crunchy-operator-{{ template "cluster_name" . }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: crunchy-operator
    repoURL: https://github.com/jatalocks/paas_cloudlet
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
