apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecrets-operator-{{ template "cluster_name" . }}
  namespace: {{ .Values.argocdNamespace }}
spec:
  destination:
    namespace: {{ .Values.spec.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  source:
    path: argocdod/apps/externalsecrets-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: cluster_name
          value: {{ template "cluster_name" . }}
        - name: USE_CERTIFICATES
          value: "{{ .Values.spec.use_custom_certificates }}"
