kind: ConfigMap
apiVersion: v1
metadata:
  name: argo-to-splunk
  namespace: argo-to-splunk
data:
  config.py: |-
    splunkUrl = '{{ .Values.configmap.splunk_event_url }}'
    splunkToken = '{{ .Values.configmap.splunk_token }}'
    argoUrl = '{{ .Values.configmap.argoUrl }}'
