configmap:
  splunkUrl: https://13.90.23.80:8088/services/collector/event
  clusterName: ocp43-dev
  splunkToken: 73361832-38a5-4edd-b61f-e1643ecbf7ed
  servicesRoutes: []
  
containers:
  repository: docker.io/meshistern
  image: app-test-to-splunk
  version: latest
