kind: ConfigMap
apiVersion: v1
metadata:
  name: quaylogs
  namespace: quaylogs
data:
  config.py: |-
    quay_repo = 'https://quay.apps.{{ .Values.configmap.fqdn }}'
    splunk_event_url = '{{ .Values.splunk.url }}'
    cluster_name = '{{ .Values.configmap.cluster_name }}'
    splunk_token = '{{ .Values.splunk.hec_token }}'
