---
kind: Secret
apiVersion: v1
metadata:
  name: pull-secret
  namespace: quaylogs
stringData:
  .dockerconfigjson: '{\"auths\":{\"quay.apps.np.{{ .Values.configmap.fqdn }}\":{\"username\":\"cloudlet_admin\",\"password\":\"Password@123\",\"auth\":\"Y2xvdWRsZXRfYWRtaW46UGFzc3dvcmRAMTIz\"}}}'
type: kubernetes.io/dockerconfigjson
