---
kind: Secret
apiVersion: v1
metadata:
  name: pull-secret
  namespace: quaylogs
stringData:
  .dockerconfigjson: {"auths":{"quay.apps.np.cloudlet-dev.com":{"username":"cloudlet_admin","password":"Password@123","auth":"Y2xvdWRsZXRfYWRtaW46UGFzc3dvcmRAMTIz","email":""}}}
type: kubernetes.io/dockerconfigjson
