---
# Source: quay-enterprise/templates/01_Salty_project.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: salty

---
# Source: salty/templates/02_Salty_Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: salty
  namespace: salty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salty
  template:
    metadata:
      labels:
        app: salty
    spec:
      containers:
      - name: salty
        image: "{{ .Values.image.source }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
