kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-test
  namespace: minio-test
data:
  config.py: |+
    bucket_name = 'mybucket'
    minio_url = 'minio-route-default.apps.ocp43-dev.cloudlet-dev.com'
    minio_access_key = 'minio'
    minio_secret_key = 'minio123'
