kind: Deployment
apiVersion: apps/v1
metadata:
  name: minio-test
  namespace: minio-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-test
  template:
    metadata:
      labels:
        app: minio-test
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: minio-test
            defaultMode: 420
      containers:
        - name: minio-test
          image: 'docker.io/meshistern/minio-test:latest'
          ports: 
            - containerPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /minio-test/src/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPilicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
