apiVersion: v1
kind: Service
metadata:
  name: speedtest-download
spec:
  selector:
    app: speedtest-download
  ports:
    - name: speedtest-download
      protocol: TCP
      port: {{.Values.PORT}}
      targetPort: {{.Values.PORT}}

