apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: certificates-status
  namespace: certificates-status
spec:
  schedule: "*/30 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    metadata:
      labels:
        app: certificates-status
    spec:
      backoffLimit: 0
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: certificates-status
                defaultMode: 420
          containers:
            - name: certificates-status
              image: 'quay.io/{{ .Values.containers.repository }}/{{ .Values.containers.image }}:{{ .Values.containers.version }}'
              env:
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: certificates-status
                      key: DB_USER
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: certificates-status
                      key: DB_HOST
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: certificates-status
                      key: DB_PASSWORD
                - name: BASE_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: certificates-status
                      key: BASE_DOMAIN
              volumeMounts:
                - name: config-volume
                  mountPath: /certificates-status/src/config
              imagePullPolicy: Always
          imagePullSecrets:
             - name: pull-secret
          restartPolicy: Never
