apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  accesskey: {{ if .Values.accesskey }}{{ .Values.accesskey | b64enc | quote }}{{ else }}{{randAlphaNum 20 |  b64enc | quote}}{{ end }}
  secretkey: {{ if .Values.secretkey }}{{ .Values.secretkey | b64enc | quote }}{{ else }}{{randAlphaNum 20 |  b64enc | quote}}{{ end }}
