  image:
    repository: quay.io/amitai333/sampleapp
    tag: latest
  
  PG_CLUSTER_NAME: ""
  PG_NAMESPACE: ""
  PG_PGO_VERSION: ""
  PG_STORAGE_CLASS: ""
  PG_STORAGE_SIZE: ""
  PG_IMAGE_NAME: ""
  PG_IMAGE_TAG: ""
  PG_DATABASE_NAME: ""
  PG_REPLICAS: ""
  PG_SERVICE_PREFIX: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""