kind: Deployment
apiVersion: apps/v1
metadata:
  name: argo-to-splunk
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-to-splunk
  template:
    metadata:
      labels:
        app: argo-to-splunk
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: argo-to-splunk-config
            defaultMode: 420
      containers:
        - name: argo-to-splunk
          image: 'docker.io/meshistern/argo-to-splunk:latest'
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /argocd_to_splunk/src/config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPilicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    RollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
