image:
  repository: minio/k8s-operator
  tag: 1.0.7
namespace: "quay-minio"

name: minio

accessKey: minio
secretKey: minio123

replicas: 6

minioImage:
  repository: minio/minio
  tag: latest

requests:
  memory: 512Mi
  cpu: 250m

port: 9000

diskSize: 50
clusterName: ocp43-np
baseDomain: cloudlet-dev.com
