apiVersion: v1
stringData:
  password: "{{.Values.DB_PASSWORD}}"
  username: postgres
kind: Secret
metadata:
  labels:
    pg-cluster: "{{.Values.PG_CLUSTER_NAME }}"
  name: "{{.Values.PG_CLUSTER_NAME}}-postgres-secret"
  namespace: "{{.Values.PG_NAMESPACE}}"
type: Opaque
