apiVersion: v1
kind: Secret
data:
  DB_USERNAME: {{ index .Values "DB_USERNAME" | toString | b64enc }}
  DB_PASSWORD: {{ index .Values "DB_PASSWORD" | toString | b64enc }}
metadata:
  name: 'node-{{ index .Values "PG_CLUSTER_NAME" }}-secret'
  namespace: "{{.Values.PG_NAMESPACE}}"
type: Opaque