---
apiVersion: v1
kind: Namespace
metadata:
  name: toston

---
# Source: statuson/templates/cronjob.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-argo
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/3 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    metadata:
      labels:
        app_name: {{ .Values.toston_app_label }}
        level: HIGH
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: app-argo
              image: "snir1234/app_argo:latest"
              env:
                - name: BIG_MSG
                  value: "err"
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
