---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: matoshon
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/3 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    metadata:
      labels:
        app_name: {{ .Values.toston_app_label }}
        level: HIGH
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: matoshon
              image: quay.apps.{{ .Values.configmap.fqdn }}/{{ .Values.matoshon.image.repository }}/{{ .Values.matoshon.image.name }}:{{ .Values.matoshon.image.tag }}
              env:
                - name: BIG_MSG
              imagePullPolicy: Always
              volumeMounts:
              - name: trusted-ca
                mountPath: /etc/pki/ca-trust/extracted/pem
                readOnly: true
          volumes:
          - name: trusted-ca
            configMap:
              name: trusted-ca
              items:
                - key: ca-bundle.crt 
                  path: tls-ca-bundle.pem
          imagePullSecrets:
             - name: secret    
          restartPolicy: OnFailure

