kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: matoshon_adminon
subjects:
  - kind: ServiceAccount
    name: default
    namespace: toston
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: matoshon_adminon
