kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: toston_adminon
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - machineconfiguration.openshift.io
      - ''
    resources:
      - machineconfigpools
      - nodes
