---
kind: ConfigMap
apiVersion: v1
metadata:
  name: trusted-ca
  namespace: {{ .Values.namespace }}
  labels:
    config.openshift.io/inject-trusted-cabundle: "true"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: minio-test
  namespace: {{ .Values.namespace }}
data:
  config.py: |+
    bucket_name = 'mybucket-minio-test'
    minio_url = 'minio.apps.{{ .Values.configmap.fqdn }}'
---
kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: minio-test
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/instance: minio-test-dev
spec:
  startingDeadlineSeconds: 300
  schedule: '*/2 * * * *'
  concurrencyPolicy: Replace
  jobTemplate:
    metadata:
      labels:
        app: minio-test
        app_name: {{ .Values.toston_app_label }}
        level: HIGH
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: minio-test
                defaultMode: 420
          containers:
            - name: minio-test
              image: quay.apps.{{ .Values.configmap.fqdn }}/{{ .Values.minio_test.image.repository }}/{{ .Values.minio_test.image.name }}:{{ .Values.minio_test.image.tag }}
              resources: {}
              volumeMounts:
                - name: config-volume
                  mountPath: /minio-test/src/config
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
              env:
                - name: fqdn
                  value: {{ .Values.configmap.fqdn }}
          imagePullSecrets:
             - name: secret        
          restartPolicy: Never
