---
kind: Secret
apiVersion: v1
metadata:
  name: secret
  namespace: toston
stringData:
  .dockerconfigjson: '{"auths":{"quay.apps.{{ .Values.configmap.fqdn }}":{"username":"cloudlet_admin","password":"Password@123","auth":"Y2xvdWRsZXRfYWRtaW46UGFzc3dvcmRAMTIz","email":""}}}'
type: kubernetes.io/dockerconfigjson
