---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jobjobon
  namespace: {{ .Values.namespace }}
spec:
  schedule: "*/3 * * * *"
  startingDeadlineSeconds: 300
  concurrencyPolicy: "Replace"
  jobTemplate:
    metadata:
      labels:
        app_name: {{ .Values.toston_app_label }}
        level: HIGH
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: jobjobon
              image: "hacetah726/jobjob:1"
              env:
                - name: BIG_MSG
                  value: "err"
              imagePullPolicy: IfNotPresent
          restartPolicy: Never

