apiVersion: v1
kind: Secret
data:
  DB_USERNAME: {{ index .Values "pgcluster" "DB_USERNAME" | toString | b64enc }}
  DB_PASSWORD: {{ index .Values "pgcluster" "DB_PASSWORD" | toString | b64enc }}
metadata:
  name: node-secret
  namespace: {{ .Values.namespace }}
type: Opaque