kind: ConfigMap
apiVersion: v1
metadata:
  name: argo-to-splunk-config
  namespace: argocd
data:
  config.py: |+
    argoUrl = '{{ .Values.configmap.argoUrl }}'
    appsApi = '{{ .Values.configmap.appsApi }}'
    authApi = '{{ .Values.configmap.authApi }}'
    login = '{{ .Values.configmap.login }}'
    splunkUrl = '{{ .Values.configmap.splunkUrl }}'
    splunkAuth = '{{ .Values.configmap.splunkAuth }}'

