#! /bin/bash
oc delete crd certificates.certmanager.k8s.io  
oc delete crd userpreferences.console.open-cluster-management.io  
oc delete crd userpreferences.console.open-cluster-management.io  
oc delete crd klusterletaddonconfigs.agent.open-cluster-management.io  
oc delete OAuthClient "multicloudingress"  
oc delete crd certificaterequests.certmanager.k8s.io
oc delete crd cert-manager-webhook-bdd56  
oc delete RoleBinding cert-manager-webhook-webhook-authentication-reader  
oc delete RoleBinding cert-manager-webhook-webhook-authentication-reader -n"kube-system" 
oc delete ConsoleLink acm-console-link  
oc delete CustomResourceDefinition "certificaterequests.certmanager.k8s.io"  
oc delete CustomResourceDefinition "certificaterequests.certmanager.k8s.io" -A
oc delete CustomResourceDefinition "certificaterequests.certmanager.k8s.io" -A 
oc delete RoleBinding "cert-manager-webhook-webhook-authentication-reader" -n "kube-system"
oc delete RoleBinding cert-manager-webhook-webhook-authentication-reader -n kube-system
oc delete RoleBinding -n kube-system cert-manager-webhook:webhook-authentication-reader
oc delete helmrelease cert-m  
oc delete helmrelease cert-manager-34247  
oc delete ConsoleLink "acm-console-link"  
oc delete crd challenges.certmanag  
oc delete APIService v1beta1.webhoo  
oc delete crd "clusterissuers.certmanager.k8s.io"  
oc delete CustomResourceDefinition issuers.certmanager.k8s.io  
oc delete crd "cert-manager-webhook"  
oc delete MutatingWebhookConfiguration "cert-manager-webhook"  
oc delete crd "issuers.certmanager.k8s.io"  
oc delete crd "orders.certmanager.k8s.io"  
oc delete ValidatingWebhookConfiguration "cert-manager-webhook"  
oc delete crd "orders.certmanager.k8s.io"  
oc delete crd certificates.certmanager.k8s.io  
