image:
  repository: quay.apps.{{Values.configmap.fqdn}}/cloudlet-org
  name: app_argo
  tag: "latest"

every_minutes: 3

conf:  
  argoUrl = 'https://argocd.apps.np.cloudlet-dev.com/'
  appsApi = 'api/v1/clusters'
  authApi = 'api/v1/session'
  login = {"username": "admin", "password": "redhat"}
  repoApi = 'api/v1/repositories'
  cluster_name = 'np'
  reponame = 'cloudlet'
  url = 'https://argocd.apps.np.cloudlet-dev.com/'
  verifySSl = False
